/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* 响应数据
*/
export class Model8 {
    /**
    * 总页数
    */
    'pages': number;
    /**
    * 总项目数
    */
    'items': number;
    'datas': Array<object>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pages",
            "baseName": "pages",
            "type": "number"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "number"
        },
        {
            "name": "datas",
            "baseName": "datas",
            "type": "Array<object>"
        }    ];

    static getAttributeTypeMap() {
        return Model8.attributeTypeMap;
    }
}

