/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* 响应数据
*/
export class Model2 {
    /**
    * 通行令牌
    */
    'accessToken': string;
    /**
    * 刷新令牌
    */
    'refreshToken': string;
    'user': ;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accessToken",
            "baseName": "accessToken",
            "type": "string"
        },
        {
            "name": "refreshToken",
            "baseName": "refreshToken",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": ""
        }    ];

    static getAttributeTypeMap() {
        return Model2.attributeTypeMap;
    }
}

