// tslint:disable
/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject10
 */
export interface InlineObject10 {
    /**
     * 序号
     * @type {number}
     * @memberof InlineObject10
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineObject10
     */
    leaderId: number;
    /**
     * 
     * @type {number}
     * @memberof InlineObject10
     */
    followerId: number;
}


