// tslint:disable
/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject6
 */
export interface InlineObject6 {
    /**
     * 标题
     * @type {string}
     * @memberof InlineObject6
     */
    title?: string;
    /**
     * 概要
     * @type {string}
     * @memberof InlineObject6
     */
    overview?: string;
    /**
     * 正文，Markdown
     * @type {string}
     * @memberof InlineObject6
     */
    body?: string;
    /**
     * 禁用态
     * @type {boolean}
     * @memberof InlineObject6
     */
    disable?: boolean;
    /**
     * 创建者ID
     * @type {string}
     * @memberof InlineObject6
     */
    creatorId?: string;
}


