// tslint:disable
/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Model7 } from './model7';

/**
 * 
 * @export
 * @interface InlineResponse20011
 */
export interface InlineResponse20011 {
    /**
     * 业务消息
     * @type {string}
     * @memberof InlineResponse20011
     */
    message: string;
    /**
     * 业务状态码
     * @type {number}
     * @memberof InlineResponse20011
     */
    code: number;
    /**
     * 
     * @type {Model7}
     * @memberof InlineResponse20011
     */
    data: Model7;
}


