// tslint:disable
/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse201
 */
export interface InlineResponse201 {
    /**
     * 业务消息
     * @type {string}
     * @memberof InlineResponse201
     */
    message: string;
    /**
     * 业务状态码
     * @type {number}
     * @memberof InlineResponse201
     */
    code: number;
    /**
     * 
     * @type {}
     * @memberof InlineResponse201
     */
    data:  | null;
}


