// tslint:disable
/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject9
 */
export interface InlineObject9 {
    /**
     * 序号
     * @type {number}
     * @memberof InlineObject9
     */
    id: number;
    /**
     * 标题
     * @type {string}
     * @memberof InlineObject9
     */
    title?: string;
    /**
     * 简述
     * @type {string}
     * @memberof InlineObject9
     */
    overview?: string;
    /**
     * 代码
     * @type {string}
     * @memberof InlineObject9
     */
    code?: string;
}


