// tslint:disable
/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse2007
 */
export interface InlineResponse2007 {
    /**
     * 业务消息
     * @type {string}
     * @memberof InlineResponse2007
     */
    message: string;
    /**
     * 业务状态码
     * @type {number}
     * @memberof InlineResponse2007
     */
    code: number;
    /**
     * 响应数据
     * @type {object}
     * @memberof InlineResponse2007
     */
    data: object;
}


