// tslint:disable
/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InlineResponse2005Data } from './inline-response2005-data';

/**
 * 
 * @export
 * @interface InlineResponse2005
 */
export interface InlineResponse2005 {
    /**
     * 业务消息
     * @type {string}
     * @memberof InlineResponse2005
     */
    message: string;
    /**
     * 业务状态码
     * @type {number}
     * @memberof InlineResponse2005
     */
    code: number;
    /**
     * 响应数据
     * @type {Array<InlineResponse2005Data>}
     * @memberof InlineResponse2005
     */
    data: Array<InlineResponse2005Data> | null;
}


