// tslint:disable
/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InlineResponse2005Users } from './inline-response2005-users';

/**
 * 
 * @export
 * @interface InlineResponse2005Data
 */
export interface InlineResponse2005Data {
    /**
     * 总页数
     * @type {number}
     * @memberof InlineResponse2005Data
     */
    pages: number;
    /**
     * 总行数
     * @type {number}
     * @memberof InlineResponse2005Data
     */
    total: number;
    /**
     * 
     * @type {Array<InlineResponse2005Users>}
     * @memberof InlineResponse2005Data
     */
    users: Array<InlineResponse2005Users>;
}


