// tslint:disable
/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 响应数据
 * @export
 * @interface Model8
 */
export interface Model8 {
    /**
     * 总页数
     * @type {number}
     * @memberof Model8
     */
    pages: number;
    /**
     * 总项目数
     * @type {number}
     * @memberof Model8
     */
    items: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof Model8
     */
    datas: Array<object>;
}


