// tslint:disable
/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 响应数据
 * @export
 * @interface Model7
 */
export interface Model7 {
    /**
     * 用户ID
     * @type {number}
     * @memberof Model7
     */
    userId: number;
}


