// tslint:disable
/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TiMu
 */
export interface TiMu {
    /**
     * 标题
     * @type {string}
     * @memberof TiMu
     */
    title: string;
    /**
     * 正文，Markdown
     * @type {string}
     * @memberof TiMu
     */
    body: string;
}


