// tslint:disable
/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TieZi
 */
export interface TieZi {
    /**
     * 序号
     * @type {number}
     * @memberof TieZi
     */
    id: number;
    /**
     * 标题
     * @type {string}
     * @memberof TieZi
     */
    title: string;
    /**
     * 简述
     * @type {string}
     * @memberof TieZi
     */
    overview: string;
    /**
     * 正文，Markdown
     * @type {string}
     * @memberof TieZi
     */
    body?: string;
    /**
     * 禁用态
     * @type {boolean}
     * @memberof TieZi
     */
    disable?: boolean;
    /**
     * 创建者ID
     * @type {string}
     * @memberof TieZi
     */
    creatorId?: string;
}


