// tslint:disable
/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TieMa
 */
export interface TieMa {
    /**
     * 序号
     * @type {number}
     * @memberof TieMa
     */
    id: number;
    /**
     * 标题
     * @type {string}
     * @memberof TieMa
     */
    title: string;
    /**
     * 简述
     * @type {string}
     * @memberof TieMa
     */
    overview: string;
    /**
     * 代码
     * @type {string}
     * @memberof TieMa
     */
    code: string;
}


