// tslint:disable
/**
 * OJPlus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 用户
 * @export
 * @interface User
 */
export interface User {
    /**
     * 序号
     * @type {number}
     * @memberof User
     */
    id: number;
    /**
     * 用户名，学号/工号
     * @type {string}
     * @memberof User
     */
    username: string;
    /**
     * 密码
     * @type {string}
     * @memberof User
     */
    password: string;
    /**
     * 姓名
     * @type {string}
     * @memberof User
     */
    name: string;
    /**
     * 昵称
     * @type {string}
     * @memberof User
     */
    nickname?: string;
    /**
     * 邮箱
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * 班级
     * @type {string}
     * @memberof User
     */
    className?: string;
    /**
     * 经验值
     * @type {number}
     * @memberof User
     */
    exp?: number;
    /**
     * 权限
     * @type {number}
     * @memberof User
     */
    role?: number;
    /**
     * 禁用态
     * @type {boolean}
     * @memberof User
     */
    disable?: boolean;
}


